backend:
  name: github
  repo: max-jellycat/gatsby-netlify

media_folder: static/assets
public_folder: assets

collections:
  - name: post
    label: Post
    folder: posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
